version: "3"

services:
  db:
    image: postgres:10-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - lisk
    restart: unless-stopped
    environment:
      - POSTGRES_DB=lisk_dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=lisk

  sdk-chown:
    image: lisk-sdk
    volumes:
      - ./dev_environment:/home/$USER/dev_environment
    depends_on:
      - db
    user: root
    command: chown --verbose --recursive $USER:$USER /home/$USER/dev_environment

  sdk:
    image: lisk-sdk
    volumes:
      - ./dev_environment:/home/$USER/dev_environment
    networks:
      - lisk
    depends_on:
      - sdk-chown
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    user: $USER

volumes:
  db-data:

networks:
  lisk:

